---
- name: Set Nginx config path for Debian/Ubuntu
  set_fact:
    nginx_conf_path: /etc/nginx/sites-enabled/app.conf
  when: ansible_os_family == 'Debian'

- name: Set Nginx config path for RHEL/CentOS
  set_fact:
    nginx_conf_path: /etc/nginx/conf.d/app.conf
  when: ansible_os_family == 'RedHat'

- name: Install Nginx (Debian/Ubuntu)
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Nginx (RHEL/CentOS)
  dnf:
    name: nginx
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure Nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy Nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: validate nginx